### PR TITLE
Specify use of trace context

### LINKED ISSUE #143: enforce trace context in http header
Add requirement to use the trace context as defined in W3C standard (https://www.w3.org/TR/trace-context/) for all transactions,

### PR DESCRIPTION
**Pull request by qligier**
Fixes #143 

Preview: https://build.fhir.org/ig/ehealthsuisse/ch-epr-mhealth/branches/ql_trace_context/index.html

### CODE REVIEW

**Comment by qligier** [comment]
Consecutive HTTP requests SHALL NOT have the same trace-id -> Clients SHALL use a different trace-id for each new request

Volume 1/Swiss requirements -> Appendix/Trace Context

Remove section "Authorization header"

Also include ITI-20 in scope.

Replace "EPR platform requirements" with:
Each actor shall support the traceparent header. Grouped actors shall use the same trace-id value to correlate IHE transactions.

EPR platform -> responder

**Comment by oliveregger** [comment]
@qligier Is the error in https://build.fhir.org/ig/ehealthsuisse/ch-epr-mhealth/branches/ql_trace_context/qa.html#_scratch_repo_fsh-generated_resources_AuditEvent-ex-auditProvideBundle-source due to the changments necessary in BALP?

**Comment by qligier** [comment]
https://github.com/IHE/ITI.MHD/issues/220

**Comment by qligier** [comment]
- Added a link to issue #153 in the open issues.
- Fixed the content of the example ex-auditProvideBundle-source (but the QA error is still there)

**Review by oliveregger — APPROVED** [review]

**Pull request merged**
